### ISSUE TITLE
unRaid error: Repository not found

### ISSUE THREAD

**Issue by cablecutter** [coppit/docker-templates#5]
Hi Coppit - getting a  little error here on unRaid

> root@localhost:# /usr/local/emhttp/plugins/dynamix.docker.manager/scripts/docker run -d --name="FileBotUI" --net="bridge" -e TZ="America/New_York" -p 3389:3389/tcp -v "/mnt/user/Warehouse/cablecutter/Inbox/":"/input":rw -v "/mnt/user/Warehouse/cablecutter/files/Media/":"/output":rw -v "/mnt/user/Warehouse/config/":"/config":rw coppit/filebot-ui
Unable to find image 'coppit/filebot-ui:latest' locally
latest: Pulling from coppit/filebot-ui
ee71edba89b9: Pulling fs layer
be425ce5c832: Pulling fs layer
6c6e5d678efd: Pulling fs layer
8ac93f399f1d: Pulling fs layer
62662396bfdb: Pulling fs layer
c243a8dbdb1e: Pulling fs layer
d96d74066465: Pulling fs layer
60370bf526d0: Pulling fs layer
3e700dffb153: Pulling fs layer
d928ea025e4d: Pulling fs layer
3c89976415d0: Pulling fs layer
45c2cecc0cef: Pulling fs layer
8a310af4fc80: Pulling fs layer
4e11a9586704: Pulling fs layer
9261c4b7dc9b: Pulling fs layer
c0bcfd872174: Pulling fs layer
9431b1e2795d: Pulling fs layer
02fbd8a9238e: Pulling fs layer
423a7d4a3dd3: Pulling fs layer
6f29c5d4bf5f: Pulling fs layer
d8ece43146ec: Pulling fs layer
2989b7b0e9f6: Pulling fs layer
393735167157: Pulling fs layer
764268b0d316: Pulling fs layer
da40bf90672a: Pulling fs layer
66af534ed0b4: Pulling fs layer
929b1576337b: Already exists
0c5b9fa91414: Already exists
e6a4e3ad2d5f: Already exists
7410eabbf432: Already exists
6b75a3b74964: Already exists
48c853025568: Already exists
Pulling repository coppit/filebot-ui
Repository not found

> 

Maybe you can help me out - really looking forward to using your automated FileBot

**Comment by coppit** [comment]
I just pulled it successfully from docker hub. It's not a problem with the image. Google the error, or try on the docker forums for help.
